name: build:online

on:
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: 迁出代码
        uses: actions/checkout@master

      # 安装Node
      - name: 安装node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 构建项目
      - name: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          npx pnpm i
          export PKM_VERSION_DEFAULT=$(node -pe "require('./package.json').version")
          export SEMANTIC_VERSION=`npm run semantic-release --dry-run --registry=https://registry.npmmirror.com | grep -oP 'Published release \K.*? ' | sed s/[[:space:]]//g`
          export PKM_VERSION=${SEMANTIC_VERSION:-${PKM_VERSION_DEFAULT}}-build${GITHUB_RUN_ID}
          npx pnpm build
          npm run release

      # 上传服务器
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "./dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # 目标地址
          TARGET: "/www/blog"